package com.example.mula.navigation

const val ROUTE_SPLASH = "splash_screen"
const val ROUTE_ONBOARDING = "onboarding_screen"
const val ROUTE_AUTH_LANDING = "auth_landing_screen"
const val ROUTE_LOGIN = "login_screen"
const val ROUTE_REGISTER = "register_screen"
const val ROUTE_FORGOT_PASSWORD = "forgot_password_screen"
const val ROUTE_OTP_VERIFICATION = "otp_verification_screen"
const val ROUTE_RESET_PASSWORD = "reset_password_screen"
const val ROUTE_HOME = "home_screen"
const val ROUTE_REWARDS = "rewards_screen"
const val ROUTE_NOTIFICATION = "notification_screen"
const val ROUTE_CATALOG = "catalog_screen"
const val ROUTE_STORE_SELECTION = "store_selection_screen"
const val ROUTE_PRODUCT_DETAIL = "product_detail_screen"
const val ROUTE_CHECKOUT = "checkout_screen"
const val ROUTE_ORDER_METHOD_SHEET = "order_method_sheet"
const val ROUTE_LOCATION_PICKER = "location_picker_screen"
const val ROUTE_PAYMENT_METHOD = "payment_method_screen"
const val ROUTE_QRIS_PAYMENT = "qris_payment_screen"
const val ROUTE_VOUCHER = "voucher_screen"
const val ROUTE_ORDER_HISTORY = "order_history_screen"
const val ROUTE_ORDER_HISTORY_SUCCESS_DETAIL = "order_history_success_detail_screen"
const val ROUTE_ORDER_HISTORY_FAILED_DETAIL = "order_history_failed_detail_screen"
const val ROUTE_ORDER_STATUS_PICKUP = "order_status_pickup_screen"
const val ROUTE_ORDER_STATUS_DELIVERY = "order_status_delivery_screen"
const val ROUTE_PROFILE = "profile_screen"

const val ARG_ORDER_METHOD = "order_method"
const val ARG_PRODUCT_ID = "product_id"
const val ARG_BRANCH_ID = "branch_id"
const val ARG_ORDER_ID = "order_id"
const val ARG_ENTRY_SOURCE = "entry_source"
const val ARG_PHONE_NUMBER = "phone_number"
const val ARG_PAYMENT_ID = "payment_id"

const val ROUTE_CATALOG_WITH_ARGS = "$ROUTE_CATALOG?$ARG_ORDER_METHOD={$ARG_ORDER_METHOD}"
const val ROUTE_STORE_SELECTION_WITH_ARGS = "$ROUTE_STORE_SELECTION/{$ARG_ORDER_METHOD}"
const val ROUTE_PRODUCT_DETAIL_WITH_ARGS = "$ROUTE_PRODUCT_DETAIL/{$ARG_PRODUCT_ID}"
const val ROUTE_CHECKOUT_WITH_ARGS = "$ROUTE_CHECKOUT?$ARG_ORDER_METHOD={$ARG_ORDER_METHOD}"
const val ROUTE_OTP_VERIFICATION_WITH_ARGS = "$ROUTE_OTP_VERIFICATION/{$ARG_PHONE_NUMBER}"
const val ROUTE_VOUCHER_WITH_ARGS = "$ROUTE_VOUCHER?$ARG_ENTRY_SOURCE={$ARG_ENTRY_SOURCE}"
const val ROUTE_QRIS_PAYMENT_WITH_ARGS = "$ROUTE_QRIS_PAYMENT/{$ARG_PAYMENT_ID}"
const val ROUTE_ORDER_HISTORY_SUCCESS_DETAIL_WITH_ARGS = "$ROUTE_ORDER_HISTORY_SUCCESS_DETAIL?$ARG_ORDER_ID={$ARG_ORDER_ID}"
const val ROUTE_ORDER_HISTORY_FAILED_DETAIL_WITH_ARGS = "$ROUTE_ORDER_HISTORY_FAILED_DETAIL?$ARG_ORDER_ID={$ARG_ORDER_ID}"
const val ROUTE_ORDER_STATUS_PICKUP_WITH_ARGS = "$ROUTE_ORDER_STATUS_PICKUP?$ARG_ORDER_ID={$ARG_ORDER_ID}"
const val ROUTE_ORDER_STATUS_DELIVERY_WITH_ARGS = "$ROUTE_ORDER_STATUS_DELIVERY?$ARG_ORDER_ID={$ARG_ORDER_ID}"

fun catalog_route(order_method: String): String = "$ROUTE_CATALOG?$ARG_ORDER_METHOD=$order_method"
fun store_selection_route(order_method: String): String = "$ROUTE_STORE_SELECTION/$order_method"
fun product_detail_route(product_id: String): String = "$ROUTE_PRODUCT_DETAIL/$product_id"
fun checkout_route(order_method: String): String = "$ROUTE_CHECKOUT?$ARG_ORDER_METHOD=$order_method"
fun otp_verification_route(phone_number: String): String = "$ROUTE_OTP_VERIFICATION/$phone_number"
fun voucher_route(entry_source: String): String = "$ROUTE_VOUCHER?$ARG_ENTRY_SOURCE=$entry_source"
fun qris_payment_route(payment_id: String): String = "$ROUTE_QRIS_PAYMENT/$payment_id"
fun order_history_success_detail_route(order_id: String): String = "$ROUTE_ORDER_HISTORY_SUCCESS_DETAIL?$ARG_ORDER_ID=$order_id"
fun order_history_failed_detail_route(order_id: String): String = "$ROUTE_ORDER_HISTORY_FAILED_DETAIL?$ARG_ORDER_ID=$order_id"
fun order_status_pickup_route(order_id: String): String = "$ROUTE_ORDER_STATUS_PICKUP?$ARG_ORDER_ID=$order_id"
fun order_status_delivery_route(order_id: String): String = "$ROUTE_ORDER_STATUS_DELIVERY?$ARG_ORDER_ID=$order_id"
